### ISSUE TITLE
Verbose

### ISSUE THREAD

**Issue by st084331** [andreped/livermask#16]
I apologize in advance for a possibly stupid question. But what does the --verbose flag do? I used it but didn't understand what changed

**Comment by andreped** [comment]
Hello, @st084331 ! No question is too stupid to ask :]

By setting `--verbose=1` you are increasing the verbosity, which simply means that you will get more information on what is happening during processing. Using verbose does not impact the results. It can be useful to disable verbose when running in batch mode as you may only care about sample-wise progress. On the other hand, it can be useful to enable verbose for debugging. Hope that was helpful!

**Comment by st084331** [comment]
Thanks!
