### ISSUE TITLE
Are there performance metrics for the model?

### ISSUE THREAD

**Issue by hossam-zaki** [andreped/livermask#33]
**Describe the solution you'd like**
Would just like a section in the ReadMe about how well this model performs in segmenting liver parenchyma and vessels. Will be useful in integrating it into scientific papers.

**Comment by andreped** [comment]
Hello, @hossam-zaki!

We presented performance metrics on both liver parenchyma and vessels in the Supporting Information of [this paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0282110). See Table E in Appendix S4 in the Supplementary Information (click [this link](https://doi.org/10.1371/journal.pone.0282110.s004) to download the PDF and see Table E).

I have included performance metrics below (which were reported on a local dataset against manual annotations):

| Class | DSC | HD95 |
|--------|-------------------|------------------|
| Parenchyma | 0.946±0.046 | 10.122±11.032 |
| Vessels | 0.355±0.090 | 24.872±5.161 |

**Comment by andreped** [comment]
As this could be of interest to others, I have now updated the README to include this table: https://github.com/andreped/livermask#segmentation-performance-metrics

And I have added how to cite the performance of this tool as well:
https://github.com/andreped/livermask#acknowledgements

Thank you for the great suggestion, @hossam-zaki! And best of luck with your research paper! :]

**Comment by hossam-zaki** [comment]
Thank you so much! Much appreciated!!
