### ISSUE TITLE
Model no longer accessible

### ISSUE THREAD

**Issue by andreped** [andreped/livermask#6]
Seems like the model can no longer be downloaded. I might have deleted it when accidentally when cleaning my google drive.

**Comment by andreped** [comment]
Fixed in most recent commit bc41368724cc929e9def81a50508554d1b991998

**Comment by mremise** [comment]
Awesome ! Thank you so much, it generalises well to my data

**Comment by andreped** [comment]
Happy to hear, @mremise!
